@rootURL = http://localhost:3000
@apiEP = {{rootURL}}/api/v1
@userAPI = {{apiEP}}/users
@bookPostgresqlAPI = {{apiEP}}/books


### login
POST {{userAPI}}
Content-Type: application/json

{
    "email":"jondoe@gmail.com",
    "password":"12345"
}

### Get All users
GET {{userAPI}}

###
GET http://localhost:3000/products?page=5&limit=10